language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

# command to install dependencies
install: "make"

# command to run tests
script:
    - make test
    - make lint

# install libarchive
# @see https://github.com/Changaco/python-libarchive-c/blob/master/.travis.yml
cache:
  directories:
    - /opt/python-libarchive-c

env:
  global:
    - LIBARCHIVE=/opt/python-libarchive-c/lib/libarchive.so

before_install:
  - sudo apt-get install -y zlib1g-dev liblzma-dev libbz2-dev libxml2-dev nettle-dev libattr1-dev libacl1-dev
  - "if [ ! -e $LIBARCHIVE ]; then
        wget http://libarchive.org/downloads/libarchive-3.3.2.tar.gz &&
        tar -xf libarchive-3.3.2.tar.gz && cd libarchive-3.3.2 &&
        ./configure --prefix=/opt/python-libarchive-c --disable-bsdcpio --disable-bsdtar &&
        make && sudo make install && cd .. ;
    fi"