name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt install libarchive-dev
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Check code formatting
      run: black --check .

    - name: Lint with pylint
      run: make lint

    - name: Test with pytest
      run: make test
